FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

ENV TZ=Asia/Jakarta

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    cron \
    vim \
    nano \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
